### PR TITLE
Fix ArmA 3 Protocol DLC hashes & PHP7.4 hexdec() bug

### LINKED ISSUE #405: [Ongoing Issue] ARMA 3 DLC
https://github.com/Austinb/GameQ/pull/383
https://github.com/Austinb/GameQ/issues/382
https://github.com/Austinb/GameQ/pull/379

Every ~~mod~~ DLC that get's released follows a value of a power of two. I'l just going to go ahead and fix the latest mod (Laws of War) as well as a few others named `Arma DLC`. This should prevent ongoing errors with the Arma 3 GameQ Protocol.

PR to come tonight.

Edit: I was probably really ~~drunk~~ tired when I wrote this. I meant DLC, not Mods.

### LINKED ISSUE #546: ARMA 3 tests causing PHP 7.4 to fail
The issue is the `hexdec()` call at https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Arma3.php#L156.  This is new in PHP 7.4 (https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.invalid-base-characters) but is causing PHP Unit to fail out thus causing the build to fail in PHP 7.4.  Not sure if the tests are bad or if something else is going on.   It is data sets 2_ & 4_.

Also the tests for #382 are failing for the same reason.

### LINKED ISSUE #589: Arma3 on php 8.0 gives a deprecation notice
On PHP 8.0 I get a depreciation notice as follows:

`<b>Deprecated</b>:  Invalid characters passed for attempted conversion, these have been ignored in <b>/var/www/public/src/GameQ/Protocols/Arma3.php</b> on line <b>156</b><br />
`

This is referenced  in the php manual [here](https://www.php.net/manual/en/function.hexdec.php) for the hexdec() function in php 7.4 and up `<html>
<body>

Version | Description
-- | --
7.4.0 | Passing invalid characters will now generate a deprecation notice. The result will still be computed as if the invalid characters did not exist.

</body>
</html>` 

A dirty workaround is to put the following line near the top of the file:

`error_reporting(E_ALL ^ E_DEPRECATED);`

Not sure the correct workaround to fix this for all versions of php as the manual does not say much

### PR DESCRIPTION
**Pull request by bumbummen99**
Fixes #589
Fixes #546
Fixes #405

- [x] Removed dependency on dlc hashes for naming and simply use DLC flags for it.
- [x] Fix hexdec bug, this was due to steam_id being read as pascal string, A3 protocol demands the length to be 4 bit tought with the upper nibble containing a DLC flag
- [x] Support CDLC. Right now CDLC seem to have an empty name and only 3 byte for steam id

### CODE REVIEW

**Comment by Austinb** [comment]
Looks good but all PHP constants need to be full uppercase.

**Comment by bumbummen99** [comment]
This is still WIP, we still need a way to get behind what steam_id actually is for Creator DLC since they lack the DLC bit, issue was that they are just 3byte and i would get nonsense no matter how i would decode it - would have tought for it to be the appid of the CDLC.

**Comment by bumbummen99** [comment]
@stale Not stale...well...kinda but it is on my ToDo-List!

**Comment by bumbummen99** [comment]
#608 608

**Pull request closed without merging**
