### PR TITLE
Add Third Party Provider Section

### PR DESCRIPTION
**Pull request by TitusKirch**
N/A

### CODE REVIEW

**Comment by TitusKirch** [comment]
N/A

**Comment by TitusKirch** [comment]
N/A

**Comment by Austinb** [comment]
Sorry for the delay its been a busy year.  Please merge in latest v3 with fixes for unit tests and update.  Will kick off updated CI build nd will merge once it passes.

**Comment by TitusKirch** [comment]
I did this as requested.

Unfortunately, I made a small mistake afterwards. I wanted to include the test for PHP 8.0 in my repo and had pushed it into the wrong branch. If desired, I will separate the whole thing again.

**Pull request merged**
