### PR TITLE
Added support for a few games (Retry).

### PR DESCRIPTION
**Pull request by uilson**
Added support for:
- ArmA Armed Assault (gamespy2)
- Brink
- Call of Duty 1
- Call of Duty United Offensive
- Crysis
- Crysis 2
- Swat 4 (gamespy2)
- Wolfenstein Enemy Territory

### CODE REVIEW

**Comment by uilson** [comment]
Ok all checked, no errors. 
the only errors are attributes from "phpunit.xml" file, that are not allowed.

> Runtime:  PHP 7.3.6 with Xdebug 2.7.2
Configuration: /home/travis/build/Austinb/GameQ/phpunit.xml
  Warning - The configuration file did not pass validation!
  The following problems have been detected:
  Line 11:
> - Element 'phpunit', attribute 'syntaxCheck': The attribute 'syntaxCheck' is not allowed.

>Line 24:
>  - Element 'log', attribute 'title': The attribute 'title' is not allowed.
>  - Element 'log', attribute 'charset': The attribute 'charset' is not allowed.
>  - Element 'log', attribute 'yui': The attribute 'yui' is not allowed.
>  - Element 'log', attribute 'highlight': The attribute 'highlight' is not allowed.
>  Test results may not be as expected.

**Comment by Austinb** [comment]
Still need to add tests for the games.  Once that is done will merge. I can hopefully get to it in a few days.

**Review by Austinb — CHANGES_REQUESTED** [review]
Need at least 2 tests for each game server.

**Comment by uilson** [comment]
The error Travis-CI is throwing, has to do with the missing Gamespy2 protocol, while doing the tests, I also noticed that Crysis had the wrong protocol, it's also for gamespy2 not gamespy3, so this will require that, once you have some time free you port the gamespy2 protocol from previous Gameq version, like I mentioned it in the [issue](https://github.com/Austinb/GameQ/issues/490#issue-491829896) I opened.

Regards.

**Comment by Austinb** [comment]
@uilson Please pull in latest from v3 and run it again.  Let me know if you have any issues.  Was hard to test the player/team parsing since not many games use this protocol any longer.

**Comment by Austinb** [comment]
FYI it appears the quake 3 player response is not grabbing the player names.  Have a issue open but fixing may cause some/all of your tests to fail.  Sorry about that in advance.

**Comment by Austinb** [comment]
Waiting on tests on it and will merge.  Looks good if the tests pass.

**Review by Austinb — APPROVED** [review]

**Pull request merged**
