### PR TITLE
fix issues when packets arrive late

### PR DESCRIPTION
**Pull request by fritzmg**
## Problem description

If the server does not respond right away, GameQ assumes it is offline. This is because GameQ checks if `$stream <= 0` [here](https://github.com/Austinb/GameQ/blob/v3.0.10/src/GameQ/Query/Native.php#L186). However, the return value of `stream_select` can be `0` if there was no data received _in the current [polling loop](https://github.com/Austinb/GameQ/blob/v3.0.10/src/GameQ/Query/Native.php#L176)_. Data might be received in the next loop though! This means, if a server does not respond in the first 200ms (the default value of [`stream_timeout`](https://github.com/Austinb/GameQ/blob/v3.0.10/src/GameQ/GameQ.php#L83)), GameQ breaks the polling loop and subsequently reports the server as offline.

## Real world test case

I noticed this in a real world test case, where I often receive the data from the servers in the polling loop much later. Either because the server is far away, or because there are some other network issues.

For example, if I remove the aforementioned condition and add some debugging output to show the return value of `stream_select` plus the time in milliseconds when the response was received, it might look something like this (for 3 servers):
```
GameQ\Query\Native::getResponses
$streams: 0
$streams: 0
$streams: 1
got response at 432ms
$streams: 0
$streams: 1
go response at 656ms
$streams: 0
$streams: 0
$streams: 0
$streams: 0
$streams: 0
$streams: 1
got response at 10744ms
$streams: 0
$streams: 0
$streams: 0
…
(runs until timeout is reached)
```

## Proposed fix

I removed the `$stream <= 0` condition. However, this means that the loop would always run until the [`timeout`](https://github.com/Austinb/GameQ/blob/v3.0.10/src/GameQ/GameQ.php#L80) value is reached (`3` seconds by default). To prevent this I added another condition that checks if the number of `$responses` received is equal to the number of `$sockets`. This way a server will only be considered _offline_ if it never responds within the `timeout`.

I am not sure if this is really the best way to deal with that. What do you think?

### CODE REVIEW

**Comment by Austinb** [comment]
@fritzmg Have you tried the old code and increasing the value of stream_timeout? What happens with the value change in the new version?  How do those really late responses fair?  Generally the value of stream_timeout should be larger than the round trip ping for the slowest server in the list.  The default is 200000 (200ms) and those servers are very late in responding.  Are those servers pretty far from you ping wise? Are the responses always late?  Are there specific protocols you see this in more?   

I do like the idea for the change but it will need to be tested a lot.  The overall timeout setting is a fail-safe against servers taking too long to respond or are never going to respond so the script does not run forever.  However we want to bail out as fast as we can from the loop with all of the data. How much time does your change add to the overall run time for a set of servers? Can you please provide the full php code you are using so I can test the same servers?

**Comment by fritzmg** [comment]
> Have you tried the old code and increasing the value of stream_timeout?

Yes, increasing `stream_timeout` helps but even with a huge `stream_timeout` value of 10 __seconds__ for example, the response might not arrive in the first polling loop.

> Generally the value of stream_timeout should be larger than the round trip ping for the slowest server in the list.

I know, I have played around with it, but it still does not catch this special case where some network issues occur and the response takes longer than usual.

> Are those servers pretty far from you ping wise? Are the responses always late?

Not too far. The round-trip time to those servers is between 100 and 350 ms generally - but ocassionally it spikes for a long time due to unknown network issues.

> Are there specific protocols you see this in more?

I am only testing it with `gamespy3` for https://stats.spikx.net/.

> The overall timeout setting is a fail-safe against servers taking too long to respond or are never going to respond so the script does not run forever.

I think that timeout will never be reached in the current implementation - because if a server does not respond at all (during one polling loop), `stream_select` will simply return `0` and then your polling loop will exit.

> However we want to bail out as fast as we can from the loop with all of the data. How much time does your change add to the overall run time for a set of servers?

That simply depends on how fast the server responds. Without the change, querying any servers will never take longer than ~400ms, since that is the default `stream_timeout` times two (challenge response plus data response). With the change, it simply depends on how fast the server answers. If it never answers, then the process will take `timeout` times two.

Right now it takes anywhere between 600ms and 20000ms for me ;)

> Can you please provide the full php code you are using so I can test the same servers?

```php
echo '<pre>';

require_once('vendor/autoload.php');

// init GameQ, add servers and request data

$gq = new \GameQ\GameQ();  
$gq->setOption('debug', true);
$gq->setOption('timeout', 20);
$gq->addServers([
	// Huntress D
	[
		'type' => 'gamespy3',
		'host' => '199.233.247.149:64250'
	],
	// AU
	[
		'type' => 'gamespy3',
		'host' => '175.34.23.187:64100'
	],
	// NorthenWolf
	[
		'type' => 'gamespy3',
		'host' => '135.19.221.106:64100'
	]
]);


// get the data
$time = microtime(true);
$gqresults = $gq->process();
$time = microtime(true) - $time;
echo "\nScanning duration: ".number_format( $time * 1000, 2, '.', '' )."ms\n";
echo "\nResults:\n";
var_dump($gqresults);

echo '</pre>';
```
However, keep in mind that those servers might respond fast enough anyway for you. It may be that I only experience these late responses on one particular machine from which I query the servers.

**Comment by Austinb** [comment]
I used your code and tested it with those servers but I am not getting a response with any test.  The only difference I can see is since there is no break the script will hold until timeout is reached but I end up with missing results anyway.  This is the conundrum.  How long should the script to try to wait for servers that may end up not responding anyway?  I had this same issue before when first writing v2 way back when which is also why I added the settings that allow you to be able to change some of the settings.   

I better option maybe to use a different php module to do the querying as there are limits in PHP's standard stream handling library.  I know someone had used a different querying engine for v2 which is why I added the extendible query classes in v3.  There are better options for handling streams but they have to be installed into PHP as they do not come standard.  I would love to swap out the internals of the whole querying side because that query code for reading responses still looks like garbage (to me) but it still works albeit not in all cases.

**Comment by fritzmg** [comment]
> I used your code and tested it with those servers but I am not getting a response with any test.

You need [this fix](https://github.com/Austinb/GameQ/pull/359) too, otherwise it won't work with any Crysis Wars server.

**Comment by Austinb** [comment]
Pushed into main at e538ef41e2330339d7096166da8730a78b560611. Please update and test. Open a new PR if you have any issues.

**Pull request merged**
