### PR TITLE
Added Grand Theft Auto Rage Protocol Class

### PR DESCRIPTION
**Pull request by Ruslan-700**
For this request https://github.com/Austinb/GameQ/issues/517

### CODE REVIEW

**Review by uilson — CHANGES_REQUESTED** [review]
Add at least 2 tests to prove it is working. (if you don't know how, [check the wiki section](https://github.com/Austinb/GameQ/wiki/Building-&-Running-Unit-Tests-v3))
It did not work when I tried, it's unable to parse the response.

**Comment by Austinb** [comment]
@Ruslan-700 Got to have at least 2 tests like @uilson stated.  Please commit them to this PR and will test and then merge if everything looks good.

**Review by Austinb — CHANGES_REQUESTED** [review]
Need at least two tests using data from working servers.

**Review by uilson — CHANGES_REQUESTED** [review]
To pass the Travis CI test, please fix the errors in the code indentation on the protocol.
You can see the errors in the Travis CI log.

**Review by Austinb — APPROVED** [review]

**Pull request merged**
