### PR TITLE
GoldSource protocol

### PR DESCRIPTION
**Pull request by et-nik**
Added GoldSource protocol alias.

```
$GameQ = new \GameQ\GameQ();
$GameQ->addServer([
    'type' => 'goldsource',
    'host' => '127.0.0.1:27015',
]);
$results = $GameQ->process();
```

### CODE REVIEW

**Comment by TacTicToe66** [comment]
Just curious, but is this even necessary or needed?

**Comment by Austinb** [comment]
@ET-NiK Is this for a game?  If so I need some servers and/or tests for it.

**Comment by et-nik** [comment]
> Just curious, but is this even necessary or needed?

I think, that it needed. I use it in my panel.

In all GoldSource servers settings i write 'goldsource' (Half-Life 1, Sven Coop, Adrenaline Gamer, Opposing force, Counter-Strike 1.6, etc.). Despite identical query protocol in GoldSource and Source, they have different rcon protocol. We can be confusing if naming GoldSource game as 'Source'.

@Austinb goldsource servers:
31.31.202.96:27015 (Half-Life)
31.31.202.96:27018 (Half-Life)
31.131.249.78:27015 (Opposing Force)
191.96.6.37:1337 (Sven Coop)

**Comment by Austinb** [comment]
@ET-NiK I understand what you are doing due to RCON differences but I wont accept this because it is too generic.  Generic classes are reserved for the base protocols like A2S, Quake, Unreal, etc... This library is focused on getting and returning server status information and as such I would recommend adding a class for each server you want to add.   I know that is a lot of work but this way provides more specific information into the normalized fields in the response such as game name. This will also give you a name that can be used when needing to switch to a different Rcon protocol for the older games. Maybe one day I will venture into the RCON side of things...

Since RCON is mainly for Source based games I can output the Source::source_engine property into the response as a gq_ variable if that will help from the remote control perspective.  The only outlier would be CS 1.5 but it uses the Won protocol class so that is simple enough to check for.  If adding this will help please open a new issue and it should be a quick add or you can do it yourself but tests will need to be updated as well or they will fail.

**Pull request closed without merging**
