### PR TITLE
Initial class for Stationeers protocol for #659 with tests.

### LINKED ISSUE #659: Add Stationeers Protocol
Hello Devs,

Can you please include stationeers as a protocol. Data from the server can be obtained via the portal server:
Output is already as JSON.

Link to Portal
http://[40.82.200.175:8081/list](http://40.82.200.175:8081/list)

Acer

### PR DESCRIPTION
**Pull request by Austinb**
Initial stab at the protocol class for Stationeers with simple tests.  Please provide feedback.

### CODE REVIEW

**Comment by Austinb** [comment]
For issue #659

**Comment by Erani0** [comment]
Currently you query the list to find the servers but if someone doesn't show his server in the list he will be shown as offline so it's really more advisable to wait for an official support or to enable this via the linked api.

**Comment by Austinb** [comment]
Well without any information from the game developer it is either this method or no method.  It doesn't matter to me but this PR should either be merged or closed to keep things tidy.

**Comment by Erani0** [comment]
Please Check its not working!
`{"35.134.96.237:27016":{"gq_address":"40.82.200.175","gq_dedicated":null,"gq_hostname":null,"gq_joinlink":"","gq_mapname":null,"gq_maxplayers":null,"gq_name":"Stationeers","gq_numplayers":null,"gq_online":false,"gq_password":null,"gq_port_client":27016,"gq_port_query":8081,"gq_protocol":"stationeers","gq_transport":"tcp","gq_type":"stationeers","players":[],"teams":[]}}`

**Comment by Austinb** [comment]
> Please Check its not working! `{"35.134.96.237:27016":{"gq_address":"40.82.200.175","gq_dedicated":null,"gq_hostname":null,"gq_joinlink":"","gq_mapname":null,"gq_maxplayers":null,"gq_name":"Stationeers","gq_numplayers":null,"gq_online":false,"gq_password":null,"gq_port_client":27016,"gq_port_query":8081,"gq_protocol":"stationeers","gq_transport":"tcp","gq_type":"stationeers","players":[],"teams":[]}}`

That server is not listed in the hosting list at http://40.82.200.175:8081/list.  I am not sure how you add it to that list but this list is the only known way for getting information for this type of server.

**Comment by Erani0** [comment]
5 days later I can not guarantee that the server is still in the list. i tested several servers and none worked

**Comment by Austinb** [comment]
Using the following code it still does not show the server information for your server. 

```
$gq = \GameQ\GameQ::factory();
$gq->addServer([
    'type' => 'source',
    'host' => '35.134.96.237:27016',
]);
$results = $gq->process();
print_r($results);
```
According to the post at https://stationeers.fandom.com/wiki/Dedicated_server there is a section for `-updateport` which is supposed to be the query port for the server.   See if you can make a simple query using the parent `source` protocol work. If so we can move towards that.  This is assuming the previous wiki link is accurate with its information.

**Comment by bumbummen99** [comment]
I have followed up with the official Stationeers channel.

Currently, multiplayer functionality and any form of server protocol are low priorities for the game.

From what I could gather, the host serving the JSON endpoint used in this implementation, called the *Metaserver* - is owned by the game's developer or publisher, as the game itself relies on this endpoint.
image


Depending on a third party host for the query is not at all ideal, however since this is the official server list i am okay with the current solution as far as it is well documented.

I will make some minor adjustments, document my findings and merge it,

**Pull request merged**
