### PR TITLE
Fixed error (Workaround?)

### PR DESCRIPTION
**Pull request by kraxarn**
Fixed crash for querying TS3 servers

### CODE REVIEW

**Comment by Austinb** [comment]
Does not fix the issue in #293. Also build failed.

**Comment by kraxarn** [comment]
It does, but mostly as a workaround. Using that code atm which works fine so far.

**Comment by Austinb** [comment]
Please provide server information to test against where removing the utf8_encode() function fixes the issue. Perhaps you are having another issue not related to the connection issue you posted in?  Please open a new issue with the server information so I may test.

**Comment by kraxarn** [comment]
Server is  connected locally, but server is hosted on 213.89.41.193 with default ports if you want to try

**Pull request closed without merging**
