### PR TITLE
Add dependabot

### LINKED ISSUE #643: Add dependabot
N/A

### PR DESCRIPTION
**Pull request by TitusKirch**
Closes #643

### CODE REVIEW

**Review by bumbummen99 — DISMISSED** [review]
LGTM

**Comment by bumbummen99** [comment]
Can you sign the commit with `git commit --amend --signoff -S` please?

**Comment by TitusKirch** [comment]
> Can you sign the commit with `git commit --amend --signoff -S` please?

Done 👍

**Comment by TitusKirch** [comment]
I have fixed a small commit mistake of mine

**Review by bumbummen99 — APPROVED** [review]

**Pull request merged**
