### PR TITLE
Add support The Ship game

### PR DESCRIPTION
**Pull request by rostov114**

### CODE REVIEW

**Comment by Austinb** [comment]
It appears the player response is different than the standard A2S response.  Will need an overloaded process_players() for this game.

**Comment by Austinb** [comment]
Actually the response is correct up until the last player then there is a bunch of extra data on the end.  Not sure what it is for.  You have any idea on this data?

**Comment by rostov114** [comment]
Information about the money and the players death
ship

**Comment by Austinb** [comment]
Any specs on the layout of the data?

**Pull request merged**
