### PR TITLE
Add Raknet protocol class with Minecraft Bedrock Edition protocol. 

### PR DESCRIPTION
**Pull request by Austinb**
Only real game used with this.  Normalize still needs tweaking.

### CODE REVIEW

**Comment by Austinb** [comment]
This is for #642.  Needs checking of the normalize response.  Might need to add a bit more testing around the whole magic query business which is just a bit odd.

**Comment by Austinb** [comment]
Sorry for the force push, had the wrong information for my signature.  Will be fixed moving forward.

**Comment by Erani0** [comment]
> This is for #642.  Needs checking of the normalize response.  Might need to add a bit more testing around the whole magic query business which is just a bit odd.

I'll test it in detail later and if there's an error I'll write something about it

**Comment by Austinb** [comment]
> > This is for #642.  Needs checking of the normalize response.  Might need to add a bit more testing around the whole magic query business which is just a bit odd.
> 
> I'll test it in detail later and if there's an error I'll write something about it

Sounds good.  Will finish up the testing as well once there are other tweaks that need to be made.  Also, the server tests may need to be rebuilt.

**Comment by Erani0** [comment]
So I tested it with a couple of public servers and it seems that there are servers that do not transmit the port_ipv4 and port_ipv6 port then it comes to the following error message 
Warning: Undefined array key 10 in /var/www/pterodactyl/public/test/GameQ/Protocols/Raknet.php on line 156

Warning: Undefined array key 11 in /var/www/pterodactyl/public/test/GameQ/Protocols/Raknet.php on line 157


And on none of the tested servers the player list can be displayed. Maybe this can be changed.

**Comment by Austinb** [comment]
> So I tested it with a couple of public servers and it seems that there are servers that do not transmit the port_ipv4 and port_ipv6 port then it comes to the following error message Warning: Undefined array key 10 in /var/www/pterodactyl/public/test/GameQ/Protocols/Raknet.php on line 156
> 
> Warning: Undefined array key 11 in /var/www/pterodactyl/public/test/GameQ/Protocols/Raknet.php on line 157

Please send the IP addresses and ports for those servers so I can add them as tests.  Need to make sure this class does not emit any kind of warnings/notices. 


> And on none of the tested servers the player list can be displayed. Maybe this can be changed.

Please check the Raknet protocol documents - the link is in the header of the Raknet.php file.  There is no information on gathering player information other than current and maximum player counts.

**Comment by Erani0** [comment]
this is a public Bedrock server with 15K+ Player 
151.80.79.246:19132

to test I have the following now in it so that no error is displayed 

```
        $result->add('port_ipv4', isset($info[10]) ? (int)$info[10] : 0);
        $result->add('port_ipv6', isset($info[11]) ? (int)$info[11] : 0);

```

**Pull request merged**
