### PR TITLE
Add MOHAA protocol with tests

### PR DESCRIPTION
**Pull request by Stormyy**
Add MOHAA protocol with tests

### CODE REVIEW

**Comment by Austinb** [comment]
@Stormyy Please check that branch and let me know if you have any issues.  It was a good start but was missing a couple of things is all.  Thanks for the PR!  If you are ok with it I will merge into stable and close this PR.

**Comment by Stormyy** [comment]
@Austinb The queryports is not static it is always client port + 97.
Otherwise it seems to look good and works.

Do i have to do the changes or will you? Im not very familiar with pr's yet..

**Comment by Austinb** [comment]
Ok I will check into that.  You can use my branch and merge it back in to your PR or I can make the change for the port once I can verify with some test servers.  I used your PR as the base for an issues branch and formatted it and updated the tests due to changed in PHPUnit as well.  You can see the in issues/365.

**Comment by Stormyy** [comment]
Ok i have changed the query port from static to +97 now. Also merged this branch with issues/365.

**Comment by Austinb** [comment]
Sorry for the delay.  Merging this...

**Pull request merged**
