### PR TITLE
FiveM Player List

### PR DESCRIPTION
**Pull request by Erani0**
FiveM Player List tests failed with no Reason

### CODE REVIEW

**Comment by bumbummen99** [comment]
What is the status of these changes?

**Comment by Erani0** [comment]
He always makes mistakes during the tests 
But not directly in the file of the change but in the test logs if I have seen it correctly

**Comment by Austinb** [comment]
Just an FYI the reason for the error is in the output from the test.  For this specific set of changes it is trying to use an undefined index in the normalize filter.  See https://github.com/Austinb/GameQ/runs/7991287918?check_suite_focus=true#step:8:29

The code added (then removed) should be done at the protocol level (https://github.com/Austinb/GameQ/blob/v3/src/GameQ/Protocols/Gta5m.php), not at the filter level to keep the filter as clean as possible.  The filters were designed to massage already returned data to do clean up or fill in missing holes due to differences in protocols (i.e. add max_players, strip color codes, etc...).  Any remote calls to the server(s) should be completed before the response is returned from the protocol itself.  

I can help if needed.  Just need a server to be able to test against.

**Comment by Erani0** [comment]
I have already found a solution, a new PR has already been created
https://github.com/Austinb/GameQ/pull/656

I just haven't added any test results now

**Pull request closed without merging**
