### PR TITLE
Fixed A2S_INFO request format for Source protocol.

### PR DESCRIPTION
**Pull request by Ruslan-700**
https://steamcommunity.com/discussions/forum/14/2989789048633291344/
https://developer.valvesoftware.com/wiki/Server_queries

### CODE REVIEW

**Comment by bumbummen99** [comment]
Any updates on this?

**Comment by Austinb** [comment]
All tests must pass before I will merge.  Its possible the data set for Crysis 2 needs to be fixed due to your change .

**Comment by bumbummen99** [comment]
> All tests must pass before I will merge. Its possible the data set for Crysis 2 needs to be fixed due to your change .

Looking to the history test data for Crysis 2 never was added or if it was where can i find it?
https://github.com/bumbummen99/GameQ/commit/178f1421c73ca80084c02f8c2c3fc0f3c28b5ab7#diff-30160c0d679d8a7c0b6df392c982ea903e71dda407037d3c33e84386b282d3fb

Fix: https://github.com/bumbummen99/GameQ/pull/8/commits/4a47319c8e10e07f6e706c71435bca9b8aa21e64

**Comment by Austinb** [comment]
I believe this is fixed in #591

**Pull request closed without merging**
